// <auto-generated />
using KickAround.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KickAround.Data.Migrations
{
    [DbContext(typeof(KickAroundContext))]
    [Migration("20180520123627_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KickAround.Models.Entities.Group", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdminId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("KickAround.Models.Entities.Match", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("EndDate");

                    b.Property<string>("GroupId");

                    b.Property<bool>("IsWeekly");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("KickAround.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("MatchId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KickAround.Models.Entities.Group", b =>
                {
                    b.HasOne("KickAround.Models.Entities.User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("KickAround.Models.Entities.Match", b =>
                {
                    b.HasOne("KickAround.Models.Entities.Group")
                        .WithMany("Matches")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("KickAround.Models.Entities.User", b =>
                {
                    b.HasOne("KickAround.Models.Entities.Match")
                        .WithMany("Attendees")
                        .HasForeignKey("MatchId");
                });
#pragma warning restore 612, 618
        }
    }
}
